[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/GRJ03/Numpy-Pandas/blob/main/Numpy.ipynb)

In [1]:
import numpy as np
list=[1,3,4,5]
x=np.array(list)
print(x)

[1 3 4 5]


In [2]:
y=np.arange(1,10)
print(y)
print(np.shape(y))


[1 2 3 4 5 6 7 8 9]
(9,)


In [3]:
#dimensions of array
print(y.ndim)


1


In [4]:
list=[[1,2],[3,4]]
x=np.array(list)
print(x)
print(x.ndim)
print(np.shape(x))
print(x.shape)

[[1 2]
 [3 4]]
2
(2, 2)
(2, 2)


In [5]:
z=np.zeros((6))
a=np.zeros((1,2))
a=np.ones((1,2,3))

print(z)
print(a)


[0. 0. 0. 0. 0. 0.]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
arr_dia=np.eye(4,4)
print(arr_dia)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
aab=np.linspace(0,10,num=4)
print(aab)

[ 0.          3.33333333  6.66666667 10.        ]


In [8]:
#print random numbers
random=np.random.randint(1,50,10)
print(random)

[27 26  3 29 12  2 24  2 12 16]


In [9]:
#type of in array
var=np.arange(1,10)
print(type(var))
print(var)
#elements ka type
print(var.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
int64


In [10]:
#array k element ka data type change krna ha toh ye kr
array=np.array([1,3,4,4,2],dtype="float")
print(array)
print(array.dtype)

[1. 3. 4. 4. 2.]
float64


In [11]:
#arithmetic opertaion in numpy
var1=np.array([1,2,3])
var2=np.array([4,5,6])
var3=np.array([7,8,9])
ans1=var1*var2+var3
summ=np.add(var1,var2,var3)
mod=np.mod(var1,var2)
divide=np.divide(var1,var2)
print(summ)
print(ans1)

var2=var2%2
var1=var1**3
ans2=var1*var2+var3
print(ans2)
## aur ek method ye l


[5 7 9]
[11 18 27]
[ 5 15  9]


In [12]:
# 2D array
twoD1=np.array([[1,2],[2,3]])
twoD2=np.array([[2,1],[5,4]])
sum=twoD1+twoD2
print(sum)

[[3 3]
 [7 7]]


In [13]:
arr1=np.arange(1,11)
newArr=np.cumsum(arr1)

print(arr1)
print(newArr)
print(np.max(newArr))
print(np.sqrt(newArr))
print(np.sin(newArr))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  6 10 15 21 28 36 45 55]
55
[1.         1.73205081 2.44948974 3.16227766 3.87298335 4.58257569
 5.29150262 6.         6.70820393 7.41619849]
[ 0.84147098  0.14112001 -0.2794155  -0.54402111  0.65028784  0.83665564
  0.27090579 -0.99177885  0.85090352 -0.99975517]


In [14]:
#convert 1d to 2d,3d using reshape

In [15]:
threeD=np.array([[[1,2],[3,4],[4,5]]])
print(threeD.ndim)
print(threeD.shape)
print(threeD.reshape(6))

3
(1, 3, 2)
[1 2 3 4 4 5]


In [16]:
c=[[1,2],[33,4]]
d=np.array(c)
print(c[1][1])
print(c[0][1])



4
2


In [17]:
#broadcating andar hi andar hoti h, dikhti nhi h

In [18]:
#SLICING
aloki=np.array([1,2,21,4])
grj=np.array([[1,2],[21,4]])
print(aloki[0:])
print(aloki[2:3])
print(grj[1,1:])

[ 1  2 21  4]
[21]
[4]


In [19]:
#iteration
aeaayyy=np.array([5,4,5,5])
print(aeaayyy)
for i in aeaayyy:
  print(i)
for i in range(0,4):
  print(i)
ae=np.array([[1,2,3],[4,5,6]])
for i in ae:
  for j in i:
    print(j)
# shortcut
for i in np.nditer(ae):
  print(i)



[5 4 5 5]
5
4
5
5
0
1
2
3
1
2
3
4
5
6
1
2
3
4
5
6


In [20]:
g=np.array([1,2,3])
gcopy=g.copy()
print("a:",g)
gcopy[0]=4
print(g)
print(gcopy)


a: [1 2 3]
[1 2 3]
[4 2 3]


In [21]:
v=np.array([1,2,3])
view=v.view()
view[0]=4
print(v)
print(view)




[4 2 3]
[4 2 3]


In [22]:
g=np.array([1,2,3])
gcopy=g.copy()
conc=np.concatenate((g,gcopy))
print(conc)

[1 2 3 1 2 3]


In [23]:
x=np.array([[1,2],[3,4]])
y=np.array([[1,2],[3,4]])
print(y.flatten())
# conca=np.concatenate((x,y),axis=1)
# print(conca)

[1 2 3 4]


In [24]:
#split
m=np.array_split(g,4)
print(m)

[array([1]), array([2]), array([3]), array([], dtype=int64)]


In [25]:
#search
ekarray=np.array([2,41,3,24,8])
#return index of even number ki aaray
# answer=np.where(#condition)
answer=np.where((ekarray%2==0))
print(answer)

# search sorted, kha insert kre ek value ko, uska index batga in sorted array bkl
#sort
sorted=np.sort(ekarray)
print(sorted)
index=np.searchsorted(sorted,22)
print(index)


#filter
f=[True,False,False,True,True]
print(ekarray[f])

(array([0, 3, 4]),)
[ 2  3  8 24 41]
3
[ 2 24  8]


In [26]:
ls=np.array([1,2,3,2,4,7])
# np.random.shuffle(ls)
obj=np.unique(ls)
# re=np.resize(ls,(3,2))
lsnew=np.insert(ls,(3,5),44)
# print(ls)
print(obj)
# # print(re)
print(lsnew)
lsdel=np.delete(ls,0)
print(lsdel)


[1 2 3 4 7]
[ 1  2  3 44  2  4 44  7]
[2 3 2 4 7]


In [27]:
#similar as 2darray , matrix me bas np.matrix hota h
m1=np.matrix([[1,2],[2,4]])
m2=np.matrix([[12,23],[221,41]])
#multipilcation matricx jes bkl smjh jaaa
print(m1+m2)
print(m1/m2)
print(np.subtract(m1,m2))
print(np.transpose(m2))
#swapaxes ,transpose ka naya tareeka,use 1,0 or 0,1 farak nhi padhta
print(np.swapaxes(m2,0,1))
#inverse(topic of linear algebra), #inverse of matrix
print(np.linalg.inv(m2))
#matrix ka cube/sqaure, i.e ppower
print(np.linalg.matrix_power(m1,4))
#idetntity matrix
print(np.linalg.matrix_power(m1,0))
#determinant
print(np.linalg.det(m1))

[[ 13  25]
 [223  45]]
[[0.08333333 0.08695652]
 [0.00904977 0.09756098]]
[[ -11  -21]
 [-219  -37]]
[[ 12 221]
 [ 23  41]]
[[ 12 221]
 [ 23  41]]
[[-0.00893052  0.0050098 ]
 [ 0.04813766 -0.00261381]]
[[125 250]
 [250 500]]
[[1 0]
 [0 1]]
0.0
